# Jekyll configuration

name: Yonghao
description: Welcome to Yonghao！

# url is currently only used only for the RSS feed in feed.xml
url: https://github.com/yhgao/yhgao.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl : "/yhgao.github.io"
## default date_format
date_format: 
  title: "%B-%-d-%Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language
lan: "en" 

plugins_dir: [jekyll-paginate]


highlighter: rouge
markdown: kramdown


exclude: ['README.md', 'LICENSE', "*.bak"]
